/**
 * Template engine using Handlebars
 */

import Handlebars from 'handlebars';
import { registerHelpers } from './helpers.js';
import type { SkillScene } from '../types/index.js';
import { SCENE_TEMPLATES } from './scenes/index.js';

// Embedded templates
const SKILL_MD_TEMPLATE = `---
name: {{packageName}}
description: "{{description}}"
---

# {{snakeToTitle moduleName}}

## Overview

{{overview}}

- **Package ID**: \`{{packageId}}\`
- **Module**: \`{{moduleName}}\`
- **Network**: {{network}}
- **Category**: {{category}}

## Quick Start

\`\`\`typescript
import { SuiClient } from '@mysten/sui/client';
import { Transaction } from '@mysten/sui/transactions';

const client = new SuiClient({ url: '{{rpcUrl}}' });
const tx = new Transaction();

{{#if primaryFunction}}
// Example: {{primaryFunction.name}}
tx.moveCall({
  target: \`{{packageId}}::{{moduleName}}::{{primaryFunction.name}}\`,
  arguments: [
{{#each primaryFunction.exampleArgs}}
    {{{this}}},
{{/each}}
  ],
});
{{/if}}
\`\`\`

## Entry Functions

{{#each entryFunctions}}
### \`{{name}}\`

{{semantic.description}}

{{#if (length (filterUserParams parameters))}}
| Parameter | Type | Description |
|-----------|------|-------------|
{{#each (filterUserParams parameters)}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}
{{/if}}

{{#if (length returns)}}
**Returns:**
{{#each returns}}
- \`{{tsType}}\`: {{description}}
{{/each}}
{{/if}}

{{#if (isHighRisk semantic.risk)}}
> **Warning**: {{riskBadge semantic.risk}} - {{#each semantic.warnings}}{{this}} {{/each}}
{{/if}}

{{#if (length typeParameters)}}
**Type Parameters:**
{{#each typeParameters}}
- \`{{name}}\`{{#if (length constraints)}}: {{join constraints ", "}}{{/if}}
{{/each}}
{{/if}}

---

{{/each}}

{{#if (length publicFunctions)}}
## Public Functions

{{#each publicFunctions}}
### \`{{name}}\`

{{semantic.description}}

{{#if (length (filterUserParams parameters))}}
| Parameter | Type | Description |
|-----------|------|-------------|
{{#each (filterUserParams parameters)}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}
{{/if}}

{{#if (length returns)}}
**Returns:**
{{#each returns}}
- \`{{tsType}}\`: {{description}}
{{/each}}
{{/if}}

---

{{/each}}
{{/if}}

## Types

See [references/types.md](references/types.md) for detailed type definitions.

{{#if (length events)}}
## Events

{{#each events}}
### \`{{name}}\`

{{description}}

| Field | Type | Description |
|-------|------|-------------|
{{#each fields}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}

{{/each}}
{{/if}}

{{#if (length dependencies)}}
## Dependencies

This contract depends on:

{{#each dependencies}}
- **{{moduleName}}** (\`{{packageId}}\`)
{{#each implications}}
  - {{this}}
{{/each}}
{{/each}}
{{/if}}

## Security Notes

{{#each securityNotes}}
- {{this}}
{{/each}}

---

*Generated by auto-sui-skills v{{generatorVersion}} on {{generatedAt}}*
`;

const TYPES_MD_TEMPLATE = `# Type Definitions

## Module: {{moduleName}}

Package: \`{{packageId}}\`

---

## Structs

{{#each structs}}
### \`{{name}}\`

{{#if (length abilities)}}
**Abilities**: {{join abilities ", "}}
{{/if}}

{{#if (length typeParameters)}}
**Type Parameters:**
{{#each typeParameters}}
- \`{{name}}\`{{#if (length constraints)}}: {{join constraints ", "}}{{/if}}
{{/each}}
{{/if}}

{{#if (length fields)}}
| Field | Type | Description |
|-------|------|-------------|
{{#each fields}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}
{{/if}}

---

{{/each}}

## TypeScript Types

\`\`\`typescript
{{#each structs}}
{{#unless isEvent}}
interface {{snakeToPascal name}}{{#if (length typeParameters)}}<{{#each typeParameters}}{{name}}{{#unless @last}}, {{/unless}}{{/each}}>{{/if}} {
{{#each fields}}
  {{snakeToCamel name}}: {{tsType}};
{{/each}}
}

{{/unless}}
{{/each}}
\`\`\`

---

*Generated by auto-sui-skills v{{generatorVersion}}*
`;

const CALL_TS_TEMPLATE = `/**
 * Transaction builder for {{moduleName}}
 * Package: {{packageId}}
 * Network: {{network}}
 *
 * Generated by auto-sui-skills v{{generatorVersion}}
 */

import { Transaction } from '@mysten/sui/transactions';

// Package and module constants
export const PACKAGE_ID = '{{packageId}}';
export const MODULE_NAME = '{{moduleName}}';

/**
 * Build target string for move calls
 */
function target(functionName: string): \`\${string}::\${string}::\${string}\` {
  return \`\${PACKAGE_ID}::\${MODULE_NAME}::\${functionName}\`;
}

{{#each entryFunctions}}
/**
 * {{semantic.description}}
 * {{#if (isHighRisk semantic.risk)}}
 * WARNING: {{riskBadge semantic.risk}}
 * {{/if}}
 */
export function {{snakeToCamel name}}(
  tx: Transaction,
{{#each (filterUserParams parameters)}}
  {{snakeToCamel name}}: {{tsType}},
{{/each}}
{{#if (length typeParameters)}}
  typeArgs: [{{#each typeParameters}}string{{#unless @last}}, {{/unless}}{{/each}}],
{{/if}}
): void {
  tx.moveCall({
    target: target('{{name}}'),
{{#if (length typeParameters)}}
    typeArguments: typeArgs,
{{/if}}
    arguments: [
{{#each (filterUserParams parameters)}}
{{#if isSystemObject}}
      tx.object('{{defaultValue}}'),
{{else if objectIdRequired}}
      tx.object({{snakeToCamel name}}),
{{else}}
      tx.pure.{{lowercase (first (split tsType " | "))}}({{snakeToCamel name}}),
{{/if}}
{{/each}}
    ],
  });
}

{{/each}}
`;

/**
 * Template engine class
 */
export class TemplateEngine {
  private handlebars: typeof Handlebars;
  private templates: Map<string, HandlebarsTemplateDelegate> = new Map();

  constructor() {
    this.handlebars = Handlebars.create();
    registerHelpers(this.handlebars);
    this.registerTemplates();
  }

  /**
   * Register embedded templates
   */
  private registerTemplates(): void {
    this.templates.set('skill.md', this.handlebars.compile(SKILL_MD_TEMPLATE));
    this.templates.set('types.md', this.handlebars.compile(TYPES_MD_TEMPLATE));
    this.templates.set('call.ts', this.handlebars.compile(CALL_TS_TEMPLATE));

    // Register scene-specific templates
    for (const [scene, template] of Object.entries(SCENE_TEMPLATES)) {
      this.templates.set(`scene-${scene}.md`, this.handlebars.compile(template));
    }
  }

  /**
   * Render a template with context
   */
  render(templateName: string, context: object): string {
    const template = this.templates.get(templateName);
    if (!template) {
      throw new Error(`Template "${templateName}" not found`);
    }
    return template(context);
  }

  /**
   * Render SKILL.md
   */
  renderSkillMd(context: SkillMdContext): string {
    return this.render('skill.md', context);
  }

  /**
   * Render types.md
   */
  renderTypesMd(context: TypesMdContext): string {
    return this.render('types.md', context);
  }

  /**
   * Render call.ts script
   */
  renderCallScript(context: ScriptContext): string {
    return this.render('call.ts', context);
  }

  /**
   * Render scene-specific SKILL.md
   */
  renderSceneSkillMd(scene: SkillScene, context: SceneSkillMdContext): string {
    const templateName = `scene-${scene}.md`;
    if (!this.templates.has(templateName)) {
      // Fall back to default template if scene template not found
      return this.render('skill.md', context);
    }
    return this.render(templateName, context);
  }

  /**
   * Register a custom template
   */
  registerTemplate(name: string, source: string): void {
    this.templates.set(name, this.handlebars.compile(source));
  }

  /**
   * Get underlying Handlebars instance
   */
  getHandlebars(): typeof Handlebars {
    return this.handlebars;
  }
}

// Context types for templates
export interface SkillMdContext {
  packageName: string;
  packageId: string;
  moduleName: string;
  network: string;
  rpcUrl: string;
  category: string;
  description: string;
  overview: string;
  entryFunctions: FunctionContext[];
  publicFunctions: FunctionContext[];
  events: EventContext[];
  dependencies: DependencyContext[];
  securityNotes: string[];
  primaryFunction?: PrimaryFunctionContext;
  generatorVersion: string;
  generatedAt: string;
}

export interface FunctionContext {
  name: string;
  visibility: string;
  isEntry: boolean;
  parameters: ParameterContext[];
  returns: ReturnContext[];
  typeParameters: TypeParamContext[];
  semantic: SemanticContext;
}

export interface ParameterContext {
  name: string;
  tsType: string;
  description: string;
  isOptional: boolean;
  isAutoInjected: boolean;
  isSystemObject: boolean;
  objectIdRequired: boolean;
  defaultValue?: string;
}

export interface ReturnContext {
  tsType: string;
  description: string;
}

export interface TypeParamContext {
  name: string;
  constraints: string[];
}

export interface SemanticContext {
  category: string;
  risk: string;
  description: string;
  warnings: string[];
  tags: string[];
}

export interface EventContext {
  name: string;
  description: string;
  fields: FieldContext[];
}

export interface FieldContext {
  name: string;
  tsType: string;
  description: string;
}

export interface DependencyContext {
  packageId: string;
  moduleName: string;
  implications: string[];
}

export interface PrimaryFunctionContext {
  name: string;
  exampleArgs: string[];
}

export interface TypesMdContext {
  packageId: string;
  moduleName: string;
  structs: StructContext[];
  generatorVersion: string;
}

export interface StructContext {
  name: string;
  abilities: string[];
  typeParameters: TypeParamContext[];
  fields: FieldContext[];
  isEvent: boolean;
}

export interface ScriptContext {
  packageId: string;
  moduleName: string;
  network: string;
  entryFunctions: FunctionContext[];
  generatorVersion: string;
}

/**
 * Extended context for scene-specific templates
 */
export interface SceneSkillMdContext extends SkillMdContext {
  // Additional scene context
  scene: SkillScene;
  totalFunctions: number;
  entryFunctionCount: number;
  highRiskCount: number;
  structs: StructContext[];
  /** Disassembled Move source code */
  sourceCode?: string;
}

/**
 * Create a template engine instance
 */
export function createTemplateEngine(): TemplateEngine {
  return new TemplateEngine();
}
