import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { packageId, modules, fetchedAt } = body;

    if (!packageId || !modules) {
      return NextResponse.json(
        { error: 'Invalid source data' },
        { status: 400 }
      );
    }

    // Create ZIP file
    const zip = new JSZip();

    // Add README
    const readme = `# Source Code for ${packageId}

Fetched at: ${fetchedAt}
Total modules: ${Object.keys(modules).length}

## Modules

${Object.keys(modules).map(name => `- ${name}.move`).join('\n')}

---

This is disassembled Move bytecode from on-chain package.
Generated by auto-sui-skills
`;
    zip.file('README.md', readme);

    // Add each module as a .move file
    for (const [moduleName, sourceCode] of Object.entries(modules)) {
      zip.file(`${moduleName}.move`, sourceCode as string);
    }

    // Generate ZIP
    const zipBlob = await zip.generateAsync({ type: 'blob' });

    return new NextResponse(zipBlob, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="source-${packageId.slice(0, 10)}.zip"`,
      },
    });
  } catch (error) {
    console.error('Source download error:', error);
    return NextResponse.json(
      { error: 'Failed to create download' },
      { status: 500 }
    );
  }
}
