import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

export const runtime = 'edge';

interface DownloadRequest {
  skillMd: string;
  packageName: string;
  metadata: {
    packageId: string;
    modules: string[];
    network: string;
  };
}

export async function POST(request: NextRequest) {
  try {
    const body: DownloadRequest = await request.json();
    const { skillMd, packageName, metadata } = body;

    // Create ZIP file
    const zip = new JSZip();
    const folder = zip.folder(packageName);

    if (!folder) {
      return NextResponse.json(
        { error: 'Failed to create ZIP folder' },
        { status: 500 }
      );
    }

    // Add SKILL.md
    folder.file('SKILL.md', skillMd);

    // Add metadata.json
    folder.file(
      'metadata.json',
      JSON.stringify(
        {
          ...metadata,
          generatedAt: new Date().toISOString(),
          generatorVersion: '0.1.0',
        },
        null,
        2
      )
    );

    // Add references folder
    const refsFolder = folder.folder('references');
    if (refsFolder) {
      refsFolder.file(
        'abi.json',
        JSON.stringify({ message: 'ABI data would be here' }, null, 2)
      );
    }

    // Add scripts folder
    const scriptsFolder = folder.folder('scripts');
    if (scriptsFolder) {
      scriptsFolder.file(
        'call.ts',
        `// Transaction builder for ${packageName}
// Generated by MoveWhisperer

import { Transaction } from '@mysten/sui/transactions';

export const PACKAGE_ID = '${metadata.packageId}';
`
      );
    }

    // Generate ZIP blob
    const zipBlob = await zip.generateAsync({ type: 'blob' });

    // Return as downloadable file
    return new NextResponse(zipBlob, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${packageName}.zip"`,
      },
    });
  } catch (error) {
    console.error('Download error:', error);
    return NextResponse.json(
      { error: 'Failed to create download' },
      { status: 500 }
    );
  }
}
