import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { packageId, decompiled, decompileAt } = body;

    if (!packageId || !decompiled) {
      return NextResponse.json(
        { error: 'Invalid decompiled data' },
        { status: 400 }
      );
    }

    // Create ZIP file
    const zip = new JSZip();

    // Add README
    const readme = `# Decompiled Source Code for ${packageId}

Decompiled at: ${decompileAt}
Total modules: ${Object.keys(decompiled).length}

## Modules

${Object.keys(decompiled).map(name => `- ${name}.move`).join('\n')}

---

⚠️ **Important Notes:**

1. This is **decompiled code** - it may not match the original source exactly
2. Variable names are approximated based on types
3. Comments from the original source are lost during compilation
4. Use for understanding contract logic, not for exact reproduction
5. Some complex control flow may be simplified or approximated

## Decompilation Tool

This code was decompiled using auto-sui-skills built-in decompiler.
For more accurate results, consider using:
- Revela (https://revela.verichains.io/)
- SuiGPT MAD (https://suigpt.tools/decompiler)

---

Generated by auto-sui-skills
`;
    zip.file('README.md', readme);

    // Create sources directory
    const sourcesDir = zip.folder('sources');

    // Add each module as a .move file
    for (const [moduleName, sourceCode] of Object.entries(decompiled)) {
      sourcesDir?.file(`${moduleName}.move`, sourceCode as string);
    }

    // Generate ZIP
    const zipBlob = await zip.generateAsync({ type: 'blob' });

    return new NextResponse(zipBlob, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="decompiled-${packageId.slice(0, 10)}.zip"`,
      },
    });
  } catch (error) {
    console.error('Decompiled download error:', error);
    return NextResponse.json(
      { error: 'Failed to create download' },
      { status: 500 }
    );
  }
}
