/**
 * Script generator - generates TypeScript scripts from analyzed module
 */

import type { AnalyzedModule, AnalyzedFunction } from '../types/index.js';
import { TemplateEngine, createTemplateEngine } from '../templates/engine.js';
import { VERSION } from '../index.js';

/**
 * Script generator class
 */
export class ScriptGenerator {
  private templateEngine: TemplateEngine;

  constructor() {
    this.templateEngine = createTemplateEngine();
  }

  /**
   * Generate call.ts script
   */
  generateCallScript(module: AnalyzedModule): string {
    const entryFunctions = module.functions.filter((f) => f.isEntry);

    return this.templateEngine.renderCallScript({
      packageId: module.packageId,
      moduleName: module.moduleName,
      network: module.metadata.network,
      entryFunctions: entryFunctions.map((f) => this.mapFunction(f)),
      generatorVersion: VERSION,
    });
  }

  /**
   * Generate read.ts script for public view functions
   */
  generateReadScript(module: AnalyzedModule): string {
    const publicFunctions = module.functions.filter(
      (f) => !f.isEntry && f.visibility === 'public' && f.returns.length > 0
    );

    if (publicFunctions.length === 0) {
      return this.generateEmptyReadScript(module);
    }

    const lines: string[] = [
      '/**',
      ` * Read functions for ${module.moduleName}`,
      ` * Package: ${module.packageId}`,
      ` * Network: ${module.metadata.network}`,
      ' *',
      ` * Generated by MoveWhisperer v${VERSION}`,
      ' */',
      '',
      "import { SuiClient } from '@mysten/sui/client';",
      '',
      `export const PACKAGE_ID = '${module.packageId}';`,
      `export const MODULE_NAME = '${module.moduleName}';`,
      '',
    ];

    // Generate view function wrappers
    for (const func of publicFunctions) {
      lines.push(...this.generateReadFunction(func, module));
    }

    return lines.join('\n');
  }

  /**
   * Generate empty read script
   */
  private generateEmptyReadScript(module: AnalyzedModule): string {
    return `/**
 * Read functions for ${module.moduleName}
 * Package: ${module.packageId}
 * Network: ${module.metadata.network}
 *
 * Generated by MoveWhisperer v${VERSION}
 */

// No public read functions found in this module.
// Use devInspect for simulating transactions if needed.

export const PACKAGE_ID = '${module.packageId}';
export const MODULE_NAME = '${module.moduleName}';
`;
  }

  /**
   * Generate a single read function
   */
  private generateReadFunction(
    func: AnalyzedFunction,
    _module: AnalyzedModule
  ): string[] {
    const userParams = func.parameters.filter((p) => !p.isAutoInjected);
    const camelName = this.snakeToCamel(func.name);

    const lines: string[] = [
      '/**',
      ` * ${func.semantic.description}`,
      ' */',
    ];

    // Function signature
    const paramDefs = userParams
      .map((p) => `${this.snakeToCamel(p.name)}: ${p.tsType}`)
      .join(', ');

    const returnType = func.returns.length === 1
      ? func.returns[0].tsType
      : func.returns.length > 1
        ? `[${func.returns.map((r) => r.tsType).join(', ')}]`
        : 'void';

    lines.push(`export async function ${camelName}(`);
    lines.push('  client: SuiClient,');
    if (paramDefs) {
      lines.push(`  ${paramDefs},`);
    }
    lines.push(`): Promise<${returnType}> {`);

    // Function body - use devInspect
    lines.push('  // Use devInspect to simulate the call');
    lines.push(`  const result = await client.devInspectTransactionBlock({`);
    lines.push("    sender: '0x0',");
    lines.push('    transactionBlock: {');
    lines.push(`      // Build transaction for ${func.name}`);
    lines.push('    },');
    lines.push('  });');
    lines.push('');
    lines.push('  // Parse and return result');
    lines.push(`  return result as unknown as ${returnType};`);
    lines.push('}');
    lines.push('');

    return lines;
  }

  /**
   * Map function to template context
   */
  private mapFunction(func: AnalyzedFunction) {
    return {
      name: func.name,
      visibility: func.visibility,
      isEntry: func.isEntry,
      parameters: func.parameters.map((p) => ({
        name: p.name,
        tsType: p.tsType,
        description: p.description,
        isOptional: p.isOptional,
        isAutoInjected: p.isAutoInjected,
        isSystemObject: p.isSystemObject,
        objectIdRequired: p.objectIdRequired,
        defaultValue: p.defaultValue,
      })),
      returns: func.returns,
      typeParameters: func.typeParameters,
      semantic: func.semantic,
    };
  }

  /**
   * Convert snake_case to camelCase
   */
  private snakeToCamel(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }
}

/**
 * Create a script generator instance
 */
export function createScriptGenerator(): ScriptGenerator {
  return new ScriptGenerator();
}
