/**
 * Custom Scene Template
 * Allows users to define their own scene with a custom prompt/focus
 */

export const CUSTOM_SCENE_TEMPLATE = `---
name: {{packageName}}
description: "{{description}}"
scene: custom
custom_scene_name: "{{customSceneName}}"
---

# {{snakeToTitle moduleName}} - {{customSceneName}}

{{#if customSceneDescription}}
> {{customSceneDescription}}
{{/if}}

## Contract Overview

| Property | Value |
|----------|-------|
| Package ID | \`{{packageId}}\` |
| Module | \`{{moduleName}}\` |
| Network | {{network}} |
| Category | {{category}} |

{{overview}}

---

## Module Structure

### Entry Functions ({{entryFunctionCount}})

{{#each entryFunctions}}
#### \`{{name}}\`

{{semantic.description}}

{{#if (isHighRisk semantic.risk)}}
> ⚠️ **{{riskBadge semantic.risk}}** - {{#each semantic.warnings}}{{this}} {{/each}}
{{/if}}

{{#if (length (filterUserParams parameters))}}
**Parameters:**

| Name | Type | Required | Description |
|------|------|----------|-------------|
{{#each (filterUserParams parameters)}}
| \`{{name}}\` | \`{{tsType}}\` | {{#if isOptional}}No{{else}}Yes{{/if}} | {{description}} |
{{/each}}
{{/if}}

{{#if (length typeParameters)}}
**Type Arguments:**
{{#each typeParameters}}
- \`{{name}}\`{{#if (length constraints)}} ({{join constraints ", "}}){{/if}}
{{/each}}
{{/if}}

{{#if (length returns)}}
**Returns:**
{{#each returns}}
- \`{{tsType}}\` - {{description}}
{{/each}}
{{/if}}

**Example:**
\`\`\`typescript
tx.moveCall({
  target: \`{{../packageId}}::{{../moduleName}}::{{name}}\`,
{{#if (length typeParameters)}}
  typeArguments: [{{#each typeParameters}}'0x2::sui::SUI'{{#unless @last}}, {{/unless}}{{/each}}],
{{/if}}
  arguments: [
{{#each (filterUserParams parameters)}}
{{#if isSystemObject}}
    tx.object('{{defaultValue}}'),
{{else if objectIdRequired}}
    tx.object({{snakeToCamel name}}Id),
{{else}}
    tx.pure.{{mapToPureType tsType}}({{snakeToCamel name}}),
{{/if}}
{{/each}}
  ],
});
\`\`\`

---

{{/each}}

{{#if (length publicFunctions)}}
### Public Functions (Composable)

{{#each publicFunctions}}
#### \`{{name}}\`

{{semantic.description}}

{{#if (length (filterUserParams parameters))}}
| Parameter | Type | Description |
|-----------|------|-------------|
{{#each (filterUserParams parameters)}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}
{{/if}}

{{#if (length returns)}}
**Returns:** {{#each returns}}\`{{tsType}}\`{{#unless @last}}, {{/unless}}{{/each}}
{{/if}}

---

{{/each}}
{{/if}}

## Type Definitions

{{#each structs}}
{{#unless isEvent}}
### {{snakeToPascal name}}

{{#if (length abilities)}}
**Abilities:** \`{{join abilities ", "}}\`
{{/if}}

{{#if (length fields)}}
| Field | Type | Description |
|-------|------|-------------|
{{#each fields}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}
{{/if}}

---

{{/unless}}
{{/each}}

{{#if (length events)}}
## Events

{{#each events}}
### {{name}}

{{description}}

| Field | Type | Description |
|-------|------|-------------|
{{#each fields}}
| \`{{name}}\` | \`{{tsType}}\` | {{description}} |
{{/each}}

{{/each}}
{{/if}}

{{#if (length dependencies)}}
## Dependencies

{{#each dependencies}}
### {{moduleName}}
- Package: \`{{packageId}}\`
{{#each implications}}
- {{this}}
{{/each}}
{{/each}}
{{/if}}

## Quick Start

\`\`\`typescript
import { SuiClient } from '@mysten/sui/client';
import { Transaction } from '@mysten/sui/transactions';

const client = new SuiClient({ url: '{{rpcUrl}}' });
const tx = new Transaction();

{{#if primaryFunction}}
// Call {{primaryFunction.name}}
tx.moveCall({
  target: \`{{packageId}}::{{moduleName}}::{{primaryFunction.name}}\`,
  arguments: [
{{#each primaryFunction.exampleArgs}}
    {{{this}}},
{{/each}}
  ],
});

const result = await client.signAndExecuteTransaction({
  transaction: tx,
  signer: keypair,
});
{{/if}}
\`\`\`

{{#if customFocusAreas}}
## Focus Areas

{{#each customFocusAreas}}
- {{this}}
{{/each}}
{{/if}}

## Security Notes

{{#each securityNotes}}
- {{this}}
{{/each}}

{{#if sourceCode}}
## Source Code

<details>
<summary>View Disassembled Move Source</summary>

\`\`\`move
{{{sourceCode}}}
\`\`\`

</details>
{{/if}}

---

*Generated by auto-sui-skills v{{generatorVersion}} | Custom Scene: {{customSceneName}} | {{generatedAt}}*
`;
